### ISSUE TITLE
Error 00732 

### ISSUE THREAD

**Issue by CJustice77** [Riverscapes/pyGUT#6]
Hi there,

I'm trying to run the GUT tool version 2.2.1 using an example dataset from the Asotin River that I downloaded from Utah State University Fluvial Geomorphology course materials (https://riverscapes.github.io/Fluvial-Geomorphology/Assignments/module-08_GUT.html). I get the following error message: RuntimeError: ERROR 000732: Input Raster: Dataset C:\pyGUT_2.2.1\GUT-Asotin-ASW00001-NF-F4_P1BR\Test\Inputs\EvidenceLayers/bfCh.tif does not exist or is not supported (see screen shot of error message below). Any idea what I'm doing wrong? The forward slash after EvidenceLayers looks suspicious to me, but I'm not a Python coder so I'll leave that question to the experts. I was getting this same error when running my the tool on my own dataset.

![image](https://user-images.githubusercontent.com/25647069/131570143-222594a4-963f-4706-9ecc-8e1201742ba5.png)

Thanks for any help you can provide.

Casey

**Comment by joewheaton** [comment]
Called @CJustice77 and the error above was simply because the Tier 1 and Tier 2 stuff was commented out at bottom of `config.py`. It was:

``` python
# tierFunctions.tier1(**myVars)
# tierFunctions.tier2(**myVars)
tierFunctions.tier3(**myVars)
# tierFunctions.tier3_subGU(**myVars)

```

We had @CJustice77 uncomment to 
``` python
tierFunctions.tier1(**myVars)
tierFunctions.tier2(**myVars)
tierFunctions.tier3(**myVars)
tierFunctions.tier3_subGU(**myVars)

```
and that brought up another error. His inputs were sitting in:
`C:\pyGUT2.2.1\GUT-Asotin-ASW00001-NF-F4_P1BR\Test\Inputs`
but his project level parameters were:
``` Python
# ---------------------------------------------------------------------
#  Project Level Parameters
workspace      = r'C:\pyGUT2.2.1\GUT-Asotin-ASW00001-NF-F4_P1BR\Test\Input'
runFolderName  = 'GUT_2.1\Run_01'
```
So the tool was crashing looking for inputs in the `C:\pyGUT2.2.1\GUT-Asotin-ASW00001-NF-F4_P1BR\Test\Inputs\Inputs` folder.

So we changed to:
``` Python
# ---------------------------------------------------------------------
#  Project Level Parameters
workspace      = r'C:\pyGUT2.2.1\GUT-Asotin-ASW00001-NF-F4_P1BR\Test'
runFolderName  = 'GUT_2.1\Run_01'
```
and everything ran fine. @philipbaileynar this is so screaming for us to build that proper QGIS GUT Plugin eh?

**Comment by philipbaileynar** [comment]
YES!
